### ISSUE TITLE
view.php not implemented.

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-mod_timetableevents#3]
the view.php file doesn't seem to be implemented correctly - it should probably do something like the view.php in mod/label - at the moment it just shows an empty page.

There are a few different ways that users can get to this page - like the mod/timetableevents/index.php page (and possibly log entries etc.) so good to have a sensible redirect in place if someone manages to find their way to the view.php page. 

This is a low used process so I don't think we'd block plugins db approval on this but would be good to fix anyway.

**Comment by sarahjcotton** [comment]
I think I'd originally intended to implement this but the actual view wouldn't be very useful as it's more of a resource than an activity and possibly difficult to make sense of out of context. I suppose the summary text could be helpful for teachers trying to plan the page out though? e.g. All the groups and their date ranges, as opposed to switching to each group to view from within the course page.

**Comment by marxjohnson** [comment]
For now, I've made it do the same as mod_label, it redirects to the section of the course view page where the instance is displayed.
